---
# Secret for backend application database credentials
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: movie-analyzer
type: Opaque
data:
  # movieuser:moviepass (base64 encoded) - for backend application
  DB_USERNAME: bW92aWV1c2Vy
  DB_PASSWORD: bW92aWVwYXNz 