---
# ConfigMap for database initialization (Fixed PostgreSQL syntax)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.name }}-init
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.postgres.name }}
data:
  init.sql: |
    -- PostgreSQL initialization script - Fixed to match backend schema
    
    -- Create user for the application (PostgreSQL syntax)
    CREATE USER movieuser WITH ENCRYPTED PASSWORD 'moviepass';
    
    -- Grant privileges on database
    GRANT ALL PRIVILEGES ON DATABASE moviereviews TO movieuser;
    
    -- Grant schema permissions to user
    GRANT ALL ON SCHEMA public TO movieuser;
    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO movieuser;
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO movieuser;
    
    -- Create reviews table (PostgreSQL syntax with BIGSERIAL, matching backend entity)
    CREATE TABLE IF NOT EXISTS reviews (
        id BIGSERIAL PRIMARY KEY,
        movie_id VARCHAR(255) NOT NULL,
        review_text VARCHAR(2000) NOT NULL,
        sentiment VARCHAR(50),
        sentiment_score DOUBLE PRECISION,
        rating DOUBLE PRECISION,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    -- Create indexes for better performance
    CREATE INDEX IF NOT EXISTS idx_reviews_movie_id ON reviews(movie_id);
    CREATE INDEX IF NOT EXISTS idx_reviews_created_at ON reviews(created_at);
    CREATE INDEX IF NOT EXISTS idx_reviews_sentiment ON reviews(sentiment);
    
    -- Grant table permissions to movieuser
    GRANT ALL PRIVILEGES ON TABLE reviews TO movieuser;
    GRANT USAGE, SELECT ON SEQUENCE reviews_id_seq TO movieuser;
    
    -- Insert sample data (PostgreSQL syntax with ON CONFLICT, using correct movie_id field)
    INSERT INTO reviews (movie_id, review_text, sentiment, sentiment_score, rating, created_at) VALUES
    ('shawshank', 'This is an absolutely incredible movie! The story is so inspiring and the acting is phenomenal.', 'positive', 0.95, 4.8, '2024-01-15 10:30:00'),
    ('inception', 'Mind-bending plot that keeps you thinking long after the credits roll. Christopher Nolan at his finest.', 'positive', 0.88, 4.6, '2024-01-16 14:22:00'),
    ('interstellar', 'A beautiful exploration of love, time, and space. Visually stunning with an emotional core.', 'positive', 0.92, 4.7, '2024-01-17 09:15:00'),
    ('fight-club', 'Dark and twisted but brilliantly executed. Not for everyone but definitely memorable.', 'neutral', 0.65, 3.8, '2024-01-18 16:45:00'),
    ('gladiator', 'Epic historical drama with Russell Crowe delivering a powerful performance.', 'positive', 0.85, 4.4, '2024-01-19 11:30:00'),
    ('dark-knight', 'Heath Ledger''s Joker is absolutely legendary. A masterpiece of the superhero genre.', 'positive', 0.93, 4.9, '2024-01-20 13:20:00'),
    ('shawshank', 'While well-made, I found it a bit slow for my taste. Good but not great.', 'neutral', 0.45, 3.2, '2024-01-21 15:10:00'),
    ('inception', 'Too confusing and pretentious. I couldn''t follow the plot at all.', 'negative', 0.25, 2.1, '2024-01-22 18:30:00')
    ON CONFLICT (id) DO NOTHING; 