---
# Secret for PostgreSQL database initialization
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.postgres.name }}
type: Opaque
data:
  # postgres:postgres (base64 encoded) - for database initialization
  POSTGRES_USER: {{ .Values.postgres.secret.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.postgres.secret.POSTGRES_DB }} 