---
# Model Service
apiVersion: v1
kind: Service
metadata:
  name: model
  namespace: movie-analyzer
  labels:
    app: model
spec:
  selector:
    app: model
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP 