---
# Secret for PostgreSQL database initialization
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: movie-analyzer
type: Opaque
data:
  # postgres:postgres (base64 encoded) - for database initialization
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: bW92aWVyZXZpZXdz 