---
# Database Service
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: movie-analyzer
  labels:
    app: database
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP 